/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Body7 {
  
  @SerializedName("userId")
  private String userId = null;
  @SerializedName("trueOrFalse")
  private Boolean trueOrFalse = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUserId() {
    return userId;
  }
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   * Set to true, if you would like to make the chat a favorite. Set to false if you would like to unfavorite a chat
   **/
  @ApiModelProperty(value = "Set to true, if you would like to make the chat a favorite. Set to false if you would like to unfavorite a chat")
  public Boolean getTrueOrFalse() {
    return trueOrFalse;
  }
  public void setTrueOrFalse(Boolean trueOrFalse) {
    this.trueOrFalse = trueOrFalse;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body7 body7 = (Body7) o;
    return (this.userId == null ? body7.userId == null : this.userId.equals(body7.userId)) &&
        (this.trueOrFalse == null ? body7.trueOrFalse == null : this.trueOrFalse.equals(body7.trueOrFalse));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.userId == null ? 0: this.userId.hashCode());
    result = 31 * result + (this.trueOrFalse == null ? 0: this.trueOrFalse.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body7 {\n");
    
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("  trueOrFalse: ").append(trueOrFalse).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
