/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Body10 {
  
  @SerializedName("request_send")
  private String requestSend = null;
  @SerializedName("request_receiver")
  private String requestReceiver = null;
  @SerializedName("status")
  private String status = null;
  @SerializedName("reportBlockedUser")
  private String reportBlockedUser = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRequestSend() {
    return requestSend;
  }
  public void setRequestSend(String requestSend) {
    this.requestSend = requestSend;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRequestReceiver() {
    return requestReceiver;
  }
  public void setRequestReceiver(String requestReceiver) {
    this.requestReceiver = requestReceiver;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getReportBlockedUser() {
    return reportBlockedUser;
  }
  public void setReportBlockedUser(String reportBlockedUser) {
    this.reportBlockedUser = reportBlockedUser;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body10 body10 = (Body10) o;
    return (this.requestSend == null ? body10.requestSend == null : this.requestSend.equals(body10.requestSend)) &&
        (this.requestReceiver == null ? body10.requestReceiver == null : this.requestReceiver.equals(body10.requestReceiver)) &&
        (this.status == null ? body10.status == null : this.status.equals(body10.status)) &&
        (this.reportBlockedUser == null ? body10.reportBlockedUser == null : this.reportBlockedUser.equals(body10.reportBlockedUser));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.requestSend == null ? 0: this.requestSend.hashCode());
    result = 31 * result + (this.requestReceiver == null ? 0: this.requestReceiver.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.reportBlockedUser == null ? 0: this.reportBlockedUser.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body10 {\n");
    
    sb.append("  requestSend: ").append(requestSend).append("\n");
    sb.append("  requestReceiver: ").append(requestReceiver).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  reportBlockedUser: ").append(reportBlockedUser).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
