/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Body12 {
  
  @SerializedName("userId")
  private String userId = null;
  @SerializedName("call")
  private String call = null;
  @SerializedName("chatId")
  private String chatId = null;
  @SerializedName("finishedAt")
  private String finishedAt = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUserId() {
    return userId;
  }
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCall() {
    return call;
  }
  public void setCall(String call) {
    this.call = call;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getChatId() {
    return chatId;
  }
  public void setChatId(String chatId) {
    this.chatId = chatId;
  }

  /**
   * The finishedAt attribute is the date time a call was finished (end).
   **/
  @ApiModelProperty(value = "The finishedAt attribute is the date time a call was finished (end).")
  public String getFinishedAt() {
    return finishedAt;
  }
  public void setFinishedAt(String finishedAt) {
    this.finishedAt = finishedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body12 body12 = (Body12) o;
    return (this.userId == null ? body12.userId == null : this.userId.equals(body12.userId)) &&
        (this.call == null ? body12.call == null : this.call.equals(body12.call)) &&
        (this.chatId == null ? body12.chatId == null : this.chatId.equals(body12.chatId)) &&
        (this.finishedAt == null ? body12.finishedAt == null : this.finishedAt.equals(body12.finishedAt));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.userId == null ? 0: this.userId.hashCode());
    result = 31 * result + (this.call == null ? 0: this.call.hashCode());
    result = 31 * result + (this.chatId == null ? 0: this.chatId.hashCode());
    result = 31 * result + (this.finishedAt == null ? 0: this.finishedAt.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body12 {\n");
    
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("  call: ").append(call).append("\n");
    sb.append("  chatId: ").append(chatId).append("\n");
    sb.append("  finishedAt: ").append(finishedAt).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
