/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Body {
  
  @SerializedName("mediaId")
  private String mediaId = null;
  @SerializedName("id")
  private BigDecimal id = null;
  @SerializedName("first_name")
  private String firstName = null;
  @SerializedName("last_name")
  private String lastName = null;
  @SerializedName("phone")
  private String phone = null;
  @SerializedName("country_code")
  private String countryCode = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("profile_picture_string")
  private String profilePictureString = null;
  @SerializedName("avatar")
  private String avatar = null;
  @SerializedName("verified")
  private Boolean verified = null;
  @SerializedName("passcode")
  private String passcode = null;
  @SerializedName("passcode_expiration")
  private String passcodeExpiration = null;
  @SerializedName("socket_id")
  private String socketId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMediaId() {
    return mediaId;
  }
  public void setMediaId(String mediaId) {
    this.mediaId = mediaId;
  }

  /**
   * Unique identifer
   **/
  @ApiModelProperty(value = "Unique identifer")
  public BigDecimal getId() {
    return id;
  }
  public void setId(BigDecimal id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPhone() {
    return phone;
  }
  public void setPhone(String phone) {
    this.phone = phone;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCountryCode() {
    return countryCode;
  }
  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getProfilePictureString() {
    return profilePictureString;
  }
  public void setProfilePictureString(String profilePictureString) {
    this.profilePictureString = profilePictureString;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAvatar() {
    return avatar;
  }
  public void setAvatar(String avatar) {
    this.avatar = avatar;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getVerified() {
    return verified;
  }
  public void setVerified(Boolean verified) {
    this.verified = verified;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPasscode() {
    return passcode;
  }
  public void setPasscode(String passcode) {
    this.passcode = passcode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPasscodeExpiration() {
    return passcodeExpiration;
  }
  public void setPasscodeExpiration(String passcodeExpiration) {
    this.passcodeExpiration = passcodeExpiration;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSocketId() {
    return socketId;
  }
  public void setSocketId(String socketId) {
    this.socketId = socketId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body body = (Body) o;
    return (this.mediaId == null ? body.mediaId == null : this.mediaId.equals(body.mediaId)) &&
        (this.id == null ? body.id == null : this.id.equals(body.id)) &&
        (this.firstName == null ? body.firstName == null : this.firstName.equals(body.firstName)) &&
        (this.lastName == null ? body.lastName == null : this.lastName.equals(body.lastName)) &&
        (this.phone == null ? body.phone == null : this.phone.equals(body.phone)) &&
        (this.countryCode == null ? body.countryCode == null : this.countryCode.equals(body.countryCode)) &&
        (this.email == null ? body.email == null : this.email.equals(body.email)) &&
        (this.profilePictureString == null ? body.profilePictureString == null : this.profilePictureString.equals(body.profilePictureString)) &&
        (this.avatar == null ? body.avatar == null : this.avatar.equals(body.avatar)) &&
        (this.verified == null ? body.verified == null : this.verified.equals(body.verified)) &&
        (this.passcode == null ? body.passcode == null : this.passcode.equals(body.passcode)) &&
        (this.passcodeExpiration == null ? body.passcodeExpiration == null : this.passcodeExpiration.equals(body.passcodeExpiration)) &&
        (this.socketId == null ? body.socketId == null : this.socketId.equals(body.socketId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.mediaId == null ? 0: this.mediaId.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.firstName == null ? 0: this.firstName.hashCode());
    result = 31 * result + (this.lastName == null ? 0: this.lastName.hashCode());
    result = 31 * result + (this.phone == null ? 0: this.phone.hashCode());
    result = 31 * result + (this.countryCode == null ? 0: this.countryCode.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.profilePictureString == null ? 0: this.profilePictureString.hashCode());
    result = 31 * result + (this.avatar == null ? 0: this.avatar.hashCode());
    result = 31 * result + (this.verified == null ? 0: this.verified.hashCode());
    result = 31 * result + (this.passcode == null ? 0: this.passcode.hashCode());
    result = 31 * result + (this.passcodeExpiration == null ? 0: this.passcodeExpiration.hashCode());
    result = 31 * result + (this.socketId == null ? 0: this.socketId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body {\n");
    
    sb.append("  mediaId: ").append(mediaId).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  firstName: ").append(firstName).append("\n");
    sb.append("  lastName: ").append(lastName).append("\n");
    sb.append("  phone: ").append(phone).append("\n");
    sb.append("  countryCode: ").append(countryCode).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  profilePictureString: ").append(profilePictureString).append("\n");
    sb.append("  avatar: ").append(avatar).append("\n");
    sb.append("  verified: ").append(verified).append("\n");
    sb.append("  passcode: ").append(passcode).append("\n");
    sb.append("  passcodeExpiration: ").append(passcodeExpiration).append("\n");
    sb.append("  socketId: ").append(socketId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
