/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Body11 {
  
  @SerializedName("userId")
  private BigDecimal userId = null;
  @SerializedName("call")
  private String call = null;
  @SerializedName("chatId")
  private BigDecimal chatId = null;
  @SerializedName("createdAt")
  private String createdAt = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getUserId() {
    return userId;
  }
  public void setUserId(BigDecimal userId) {
    this.userId = userId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCall() {
    return call;
  }
  public void setCall(String call) {
    this.call = call;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getChatId() {
    return chatId;
  }
  public void setChatId(BigDecimal chatId) {
    this.chatId = chatId;
  }

  /**
   * The createdAt attribute is the date time a call was created (send).
   **/
  @ApiModelProperty(value = "The createdAt attribute is the date time a call was created (send).")
  public String getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body11 body11 = (Body11) o;
    return (this.userId == null ? body11.userId == null : this.userId.equals(body11.userId)) &&
        (this.call == null ? body11.call == null : this.call.equals(body11.call)) &&
        (this.chatId == null ? body11.chatId == null : this.chatId.equals(body11.chatId)) &&
        (this.createdAt == null ? body11.createdAt == null : this.createdAt.equals(body11.createdAt));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.userId == null ? 0: this.userId.hashCode());
    result = 31 * result + (this.call == null ? 0: this.call.hashCode());
    result = 31 * result + (this.chatId == null ? 0: this.chatId.hashCode());
    result = 31 * result + (this.createdAt == null ? 0: this.createdAt.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body11 {\n");
    
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("  call: ").append(call).append("\n");
    sb.append("  chatId: ").append(chatId).append("\n");
    sb.append("  createdAt: ").append(createdAt).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
