/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2009 {
  
  @SerializedName("success")
  private Boolean success = null;
  @SerializedName("successfullySentSMS")
  private List<String> successfullySentSMS = null;
  @SerializedName("unsuccessfullySentSMS")
  private List<String> unsuccessfullySentSMS = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getSuccess() {
    return success;
  }
  public void setSuccess(Boolean success) {
    this.success = success;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getSuccessfullySentSMS() {
    return successfullySentSMS;
  }
  public void setSuccessfullySentSMS(List<String> successfullySentSMS) {
    this.successfullySentSMS = successfullySentSMS;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getUnsuccessfullySentSMS() {
    return unsuccessfullySentSMS;
  }
  public void setUnsuccessfullySentSMS(List<String> unsuccessfullySentSMS) {
    this.unsuccessfullySentSMS = unsuccessfullySentSMS;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2009 inlineResponse2009 = (InlineResponse2009) o;
    return (this.success == null ? inlineResponse2009.success == null : this.success.equals(inlineResponse2009.success)) &&
        (this.successfullySentSMS == null ? inlineResponse2009.successfullySentSMS == null : this.successfullySentSMS.equals(inlineResponse2009.successfullySentSMS)) &&
        (this.unsuccessfullySentSMS == null ? inlineResponse2009.unsuccessfullySentSMS == null : this.unsuccessfullySentSMS.equals(inlineResponse2009.unsuccessfullySentSMS));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.success == null ? 0: this.success.hashCode());
    result = 31 * result + (this.successfullySentSMS == null ? 0: this.successfullySentSMS.hashCode());
    result = 31 * result + (this.unsuccessfullySentSMS == null ? 0: this.unsuccessfullySentSMS.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2009 {\n");
    
    sb.append("  success: ").append(success).append("\n");
    sb.append("  successfullySentSMS: ").append(successfullySentSMS).append("\n");
    sb.append("  unsuccessfullySentSMS: ").append(unsuccessfullySentSMS).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
