/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2007GroupChatInfo {
  
  @SerializedName("avatar")
  private String avatar = null;
  @SerializedName("id")
  private BigDecimal id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("profile_picture_string")
  private String profilePictureString = null;
  @SerializedName("adminId")
  private BigDecimal adminId = null;
  @SerializedName("chatId")
  private BigDecimal chatId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAvatar() {
    return avatar;
  }
  public void setAvatar(String avatar) {
    this.avatar = avatar;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getId() {
    return id;
  }
  public void setId(BigDecimal id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getProfilePictureString() {
    return profilePictureString;
  }
  public void setProfilePictureString(String profilePictureString) {
    this.profilePictureString = profilePictureString;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getAdminId() {
    return adminId;
  }
  public void setAdminId(BigDecimal adminId) {
    this.adminId = adminId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getChatId() {
    return chatId;
  }
  public void setChatId(BigDecimal chatId) {
    this.chatId = chatId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2007GroupChatInfo inlineResponse2007GroupChatInfo = (InlineResponse2007GroupChatInfo) o;
    return (this.avatar == null ? inlineResponse2007GroupChatInfo.avatar == null : this.avatar.equals(inlineResponse2007GroupChatInfo.avatar)) &&
        (this.id == null ? inlineResponse2007GroupChatInfo.id == null : this.id.equals(inlineResponse2007GroupChatInfo.id)) &&
        (this.name == null ? inlineResponse2007GroupChatInfo.name == null : this.name.equals(inlineResponse2007GroupChatInfo.name)) &&
        (this.profilePictureString == null ? inlineResponse2007GroupChatInfo.profilePictureString == null : this.profilePictureString.equals(inlineResponse2007GroupChatInfo.profilePictureString)) &&
        (this.adminId == null ? inlineResponse2007GroupChatInfo.adminId == null : this.adminId.equals(inlineResponse2007GroupChatInfo.adminId)) &&
        (this.chatId == null ? inlineResponse2007GroupChatInfo.chatId == null : this.chatId.equals(inlineResponse2007GroupChatInfo.chatId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.avatar == null ? 0: this.avatar.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.profilePictureString == null ? 0: this.profilePictureString.hashCode());
    result = 31 * result + (this.adminId == null ? 0: this.adminId.hashCode());
    result = 31 * result + (this.chatId == null ? 0: this.chatId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2007GroupChatInfo {\n");
    
    sb.append("  avatar: ").append(avatar).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  profilePictureString: ").append(profilePictureString).append("\n");
    sb.append("  adminId: ").append(adminId).append("\n");
    sb.append("  chatId: ").append(chatId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
