/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.Message;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse20018 {
  
  @SerializedName("success")
  private Boolean success = null;
  @SerializedName("responseMsg")
  private String responseMsg = null;
  @SerializedName("message")
  private Message message = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getSuccess() {
    return success;
  }
  public void setSuccess(Boolean success) {
    this.success = success;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getResponseMsg() {
    return responseMsg;
  }
  public void setResponseMsg(String responseMsg) {
    this.responseMsg = responseMsg;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Message getMessage() {
    return message;
  }
  public void setMessage(Message message) {
    this.message = message;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20018 inlineResponse20018 = (InlineResponse20018) o;
    return (this.success == null ? inlineResponse20018.success == null : this.success.equals(inlineResponse20018.success)) &&
        (this.responseMsg == null ? inlineResponse20018.responseMsg == null : this.responseMsg.equals(inlineResponse20018.responseMsg)) &&
        (this.message == null ? inlineResponse20018.message == null : this.message.equals(inlineResponse20018.message));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.success == null ? 0: this.success.hashCode());
    result = 31 * result + (this.responseMsg == null ? 0: this.responseMsg.hashCode());
    result = 31 * result + (this.message == null ? 0: this.message.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20018 {\n");
    
    sb.append("  success: ").append(success).append("\n");
    sb.append("  responseMsg: ").append(responseMsg).append("\n");
    sb.append("  message: ").append(message).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
