/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.InlineResponse20012MediaArray;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse20012 {
  
  @SerializedName("mediaArray")
  private List<InlineResponse20012MediaArray> mediaArray = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<InlineResponse20012MediaArray> getMediaArray() {
    return mediaArray;
  }
  public void setMediaArray(List<InlineResponse20012MediaArray> mediaArray) {
    this.mediaArray = mediaArray;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20012 inlineResponse20012 = (InlineResponse20012) o;
    return (this.mediaArray == null ? inlineResponse20012.mediaArray == null : this.mediaArray.equals(inlineResponse20012.mediaArray));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.mediaArray == null ? 0: this.mediaArray.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20012 {\n");
    
    sb.append("  mediaArray: ").append(mediaArray).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
