/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.InlineResponse2001UnreadMessages;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2001 {
  
  @SerializedName("unreadMessages")
  private List<InlineResponse2001UnreadMessages> unreadMessages = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<InlineResponse2001UnreadMessages> getUnreadMessages() {
    return unreadMessages;
  }
  public void setUnreadMessages(List<InlineResponse2001UnreadMessages> unreadMessages) {
    this.unreadMessages = unreadMessages;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
    return (this.unreadMessages == null ? inlineResponse2001.unreadMessages == null : this.unreadMessages.equals(inlineResponse2001.unreadMessages));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.unreadMessages == null ? 0: this.unreadMessages.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    
    sb.append("  unreadMessages: ").append(unreadMessages).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
