/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.InlineResponse2007Chats;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2007 {
  
  @SerializedName("success")
  private Boolean success = null;
  @SerializedName("chats")
  private List<InlineResponse2007Chats> chats = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getSuccess() {
    return success;
  }
  public void setSuccess(Boolean success) {
    this.success = success;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<InlineResponse2007Chats> getChats() {
    return chats;
  }
  public void setChats(List<InlineResponse2007Chats> chats) {
    this.chats = chats;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2007 inlineResponse2007 = (InlineResponse2007) o;
    return (this.success == null ? inlineResponse2007.success == null : this.success.equals(inlineResponse2007.success)) &&
        (this.chats == null ? inlineResponse2007.chats == null : this.chats.equals(inlineResponse2007.chats));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.success == null ? 0: this.success.hashCode());
    result = 31 * result + (this.chats == null ? 0: this.chats.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2007 {\n");
    
    sb.append("  success: ").append(success).append("\n");
    sb.append("  chats: ").append(chats).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
