/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.InlineResponse20013SharedMedia;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse20013 {
  
  @SerializedName("sharedMedia")
  private List<InlineResponse20013SharedMedia> sharedMedia = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<InlineResponse20013SharedMedia> getSharedMedia() {
    return sharedMedia;
  }
  public void setSharedMedia(List<InlineResponse20013SharedMedia> sharedMedia) {
    this.sharedMedia = sharedMedia;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20013 inlineResponse20013 = (InlineResponse20013) o;
    return (this.sharedMedia == null ? inlineResponse20013.sharedMedia == null : this.sharedMedia.equals(inlineResponse20013.sharedMedia));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.sharedMedia == null ? 0: this.sharedMedia.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20013 {\n");
    
    sb.append("  sharedMedia: ").append(sharedMedia).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
