/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.InlineResponse20020MediaArray;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse20020 {
  
  @SerializedName("success")
  private Boolean success = null;
  @SerializedName("mediaArray")
  private List<InlineResponse20020MediaArray> mediaArray = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getSuccess() {
    return success;
  }
  public void setSuccess(Boolean success) {
    this.success = success;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<InlineResponse20020MediaArray> getMediaArray() {
    return mediaArray;
  }
  public void setMediaArray(List<InlineResponse20020MediaArray> mediaArray) {
    this.mediaArray = mediaArray;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20020 inlineResponse20020 = (InlineResponse20020) o;
    return (this.success == null ? inlineResponse20020.success == null : this.success.equals(inlineResponse20020.success)) &&
        (this.mediaArray == null ? inlineResponse20020.mediaArray == null : this.mediaArray.equals(inlineResponse20020.mediaArray));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.success == null ? 0: this.success.hashCode());
    result = 31 * result + (this.mediaArray == null ? 0: this.mediaArray.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20020 {\n");
    
    sb.append("  success: ").append(success).append("\n");
    sb.append("  mediaArray: ").append(mediaArray).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
