/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.InlineResponse2001UnreadMessages;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2003 {
  
  @SerializedName("seenMessages")
  private List<InlineResponse2001UnreadMessages> seenMessages = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<InlineResponse2001UnreadMessages> getSeenMessages() {
    return seenMessages;
  }
  public void setSeenMessages(List<InlineResponse2001UnreadMessages> seenMessages) {
    this.seenMessages = seenMessages;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2003 inlineResponse2003 = (InlineResponse2003) o;
    return (this.seenMessages == null ? inlineResponse2003.seenMessages == null : this.seenMessages.equals(inlineResponse2003.seenMessages));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.seenMessages == null ? 0: this.seenMessages.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2003 {\n");
    
    sb.append("  seenMessages: ").append(seenMessages).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
