/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.InlineResponse20017MessagesFiles;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse20019 {
  
  @SerializedName("success")
  private Boolean success = null;
  @SerializedName("files")
  private List<InlineResponse20017MessagesFiles> files = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getSuccess() {
    return success;
  }
  public void setSuccess(Boolean success) {
    this.success = success;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<InlineResponse20017MessagesFiles> getFiles() {
    return files;
  }
  public void setFiles(List<InlineResponse20017MessagesFiles> files) {
    this.files = files;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20019 inlineResponse20019 = (InlineResponse20019) o;
    return (this.success == null ? inlineResponse20019.success == null : this.success.equals(inlineResponse20019.success)) &&
        (this.files == null ? inlineResponse20019.files == null : this.files.equals(inlineResponse20019.files));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.success == null ? 0: this.success.hashCode());
    result = 31 * result + (this.files == null ? 0: this.files.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20019 {\n");
    
    sb.append("  success: ").append(success).append("\n");
    sb.append("  files: ").append(files).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
