/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.math.BigDecimal;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse20015Chat {
  
  @SerializedName("id")
  private BigDecimal id = null;
  @SerializedName("groupChat")
  private Boolean groupChat = null;
  @SerializedName("privateChat")
  private Boolean privateChat = null;
  @SerializedName("participantsId")
  private List<Integer> participantsId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getId() {
    return id;
  }
  public void setId(BigDecimal id) {
    this.id = id;
  }

  /**
   * Set to true if the chat is a group chat
   **/
  @ApiModelProperty(value = "Set to true if the chat is a group chat")
  public Boolean getGroupChat() {
    return groupChat;
  }
  public void setGroupChat(Boolean groupChat) {
    this.groupChat = groupChat;
  }

  /**
   * Set tot true if the chat is a private chat
   **/
  @ApiModelProperty(value = "Set tot true if the chat is a private chat")
  public Boolean getPrivateChat() {
    return privateChat;
  }
  public void setPrivateChat(Boolean privateChat) {
    this.privateChat = privateChat;
  }

  /**
   * An array of the user Ids participating in the chat
   **/
  @ApiModelProperty(value = "An array of the user Ids participating in the chat")
  public List<Integer> getParticipantsId() {
    return participantsId;
  }
  public void setParticipantsId(List<Integer> participantsId) {
    this.participantsId = participantsId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20015Chat inlineResponse20015Chat = (InlineResponse20015Chat) o;
    return (this.id == null ? inlineResponse20015Chat.id == null : this.id.equals(inlineResponse20015Chat.id)) &&
        (this.groupChat == null ? inlineResponse20015Chat.groupChat == null : this.groupChat.equals(inlineResponse20015Chat.groupChat)) &&
        (this.privateChat == null ? inlineResponse20015Chat.privateChat == null : this.privateChat.equals(inlineResponse20015Chat.privateChat)) &&
        (this.participantsId == null ? inlineResponse20015Chat.participantsId == null : this.participantsId.equals(inlineResponse20015Chat.participantsId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.groupChat == null ? 0: this.groupChat.hashCode());
    result = 31 * result + (this.privateChat == null ? 0: this.privateChat.hashCode());
    result = 31 * result + (this.participantsId == null ? 0: this.participantsId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20015Chat {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  groupChat: ").append(groupChat).append("\n");
    sb.append("  privateChat: ").append(privateChat).append("\n");
    sb.append("  participantsId: ").append(participantsId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
