/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.InlineResponse2005NonAnsweredCalls;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2005 {
  
  @SerializedName("nonAnsweredCalls")
  private List<InlineResponse2005NonAnsweredCalls> nonAnsweredCalls = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<InlineResponse2005NonAnsweredCalls> getNonAnsweredCalls() {
    return nonAnsweredCalls;
  }
  public void setNonAnsweredCalls(List<InlineResponse2005NonAnsweredCalls> nonAnsweredCalls) {
    this.nonAnsweredCalls = nonAnsweredCalls;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2005 inlineResponse2005 = (InlineResponse2005) o;
    return (this.nonAnsweredCalls == null ? inlineResponse2005.nonAnsweredCalls == null : this.nonAnsweredCalls.equals(inlineResponse2005.nonAnsweredCalls));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.nonAnsweredCalls == null ? 0: this.nonAnsweredCalls.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2005 {\n");
    
    sb.append("  nonAnsweredCalls: ").append(nonAnsweredCalls).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
