/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.User;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2008 {
  
  @SerializedName("success")
  private Boolean success = null;
  @SerializedName("userContactsWithWhatApp")
  private List<String> userContactsWithWhatApp = null;
  @SerializedName("undeterminedPhoneNumbers")
  private List<String> undeterminedPhoneNumbers = null;
  @SerializedName("eightUsers")
  private List<User> eightUsers = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getSuccess() {
    return success;
  }
  public void setSuccess(Boolean success) {
    this.success = success;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getUserContactsWithWhatApp() {
    return userContactsWithWhatApp;
  }
  public void setUserContactsWithWhatApp(List<String> userContactsWithWhatApp) {
    this.userContactsWithWhatApp = userContactsWithWhatApp;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getUndeterminedPhoneNumbers() {
    return undeterminedPhoneNumbers;
  }
  public void setUndeterminedPhoneNumbers(List<String> undeterminedPhoneNumbers) {
    this.undeterminedPhoneNumbers = undeterminedPhoneNumbers;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<User> getEightUsers() {
    return eightUsers;
  }
  public void setEightUsers(List<User> eightUsers) {
    this.eightUsers = eightUsers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2008 inlineResponse2008 = (InlineResponse2008) o;
    return (this.success == null ? inlineResponse2008.success == null : this.success.equals(inlineResponse2008.success)) &&
        (this.userContactsWithWhatApp == null ? inlineResponse2008.userContactsWithWhatApp == null : this.userContactsWithWhatApp.equals(inlineResponse2008.userContactsWithWhatApp)) &&
        (this.undeterminedPhoneNumbers == null ? inlineResponse2008.undeterminedPhoneNumbers == null : this.undeterminedPhoneNumbers.equals(inlineResponse2008.undeterminedPhoneNumbers)) &&
        (this.eightUsers == null ? inlineResponse2008.eightUsers == null : this.eightUsers.equals(inlineResponse2008.eightUsers));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.success == null ? 0: this.success.hashCode());
    result = 31 * result + (this.userContactsWithWhatApp == null ? 0: this.userContactsWithWhatApp.hashCode());
    result = 31 * result + (this.undeterminedPhoneNumbers == null ? 0: this.undeterminedPhoneNumbers.hashCode());
    result = 31 * result + (this.eightUsers == null ? 0: this.eightUsers.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2008 {\n");
    
    sb.append("  success: ").append(success).append("\n");
    sb.append("  userContactsWithWhatApp: ").append(userContactsWithWhatApp).append("\n");
    sb.append("  undeterminedPhoneNumbers: ").append(undeterminedPhoneNumbers).append("\n");
    sb.append("  eightUsers: ").append(eightUsers).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
