/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.InlineResponse20015Chat;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse20015 {
  
  @SerializedName("chat")
  private InlineResponse20015Chat chat = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public InlineResponse20015Chat getChat() {
    return chat;
  }
  public void setChat(InlineResponse20015Chat chat) {
    this.chat = chat;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20015 inlineResponse20015 = (InlineResponse20015) o;
    return (this.chat == null ? inlineResponse20015.chat == null : this.chat.equals(inlineResponse20015.chat));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.chat == null ? 0: this.chat.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20015 {\n");
    
    sb.append("  chat: ").append(chat).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
