/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2007User {
  
  @SerializedName("avatar")
  private String avatar = null;
  @SerializedName("profile_picture_string")
  private String profilePictureString = null;
  @SerializedName("first_name")
  private String firstName = null;
  @SerializedName("last_name")
  private String lastName = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAvatar() {
    return avatar;
  }
  public void setAvatar(String avatar) {
    this.avatar = avatar;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getProfilePictureString() {
    return profilePictureString;
  }
  public void setProfilePictureString(String profilePictureString) {
    this.profilePictureString = profilePictureString;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2007User inlineResponse2007User = (InlineResponse2007User) o;
    return (this.avatar == null ? inlineResponse2007User.avatar == null : this.avatar.equals(inlineResponse2007User.avatar)) &&
        (this.profilePictureString == null ? inlineResponse2007User.profilePictureString == null : this.profilePictureString.equals(inlineResponse2007User.profilePictureString)) &&
        (this.firstName == null ? inlineResponse2007User.firstName == null : this.firstName.equals(inlineResponse2007User.firstName)) &&
        (this.lastName == null ? inlineResponse2007User.lastName == null : this.lastName.equals(inlineResponse2007User.lastName));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.avatar == null ? 0: this.avatar.hashCode());
    result = 31 * result + (this.profilePictureString == null ? 0: this.profilePictureString.hashCode());
    result = 31 * result + (this.firstName == null ? 0: this.firstName.hashCode());
    result = 31 * result + (this.lastName == null ? 0: this.lastName.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2007User {\n");
    
    sb.append("  avatar: ").append(avatar).append("\n");
    sb.append("  profilePictureString: ").append(profilePictureString).append("\n");
    sb.append("  firstName: ").append(firstName).append("\n");
    sb.append("  lastName: ").append(lastName).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
