/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.Chat;
import io.swagger.client.model.GroupChat;
import io.swagger.client.model.Message;
import io.swagger.client.model.User;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse20022 {
  
  @SerializedName("messages")
  private List<Message> messages = null;
  @SerializedName("chat")
  private List<Chat> chat = null;
  @SerializedName("groupChats")
  private List<GroupChat> groupChats = null;
  @SerializedName("users")
  private List<User> users = null;
  @SerializedName("calls")
  private List<User> calls = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Message> getMessages() {
    return messages;
  }
  public void setMessages(List<Message> messages) {
    this.messages = messages;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Chat> getChat() {
    return chat;
  }
  public void setChat(List<Chat> chat) {
    this.chat = chat;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<GroupChat> getGroupChats() {
    return groupChats;
  }
  public void setGroupChats(List<GroupChat> groupChats) {
    this.groupChats = groupChats;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<User> getUsers() {
    return users;
  }
  public void setUsers(List<User> users) {
    this.users = users;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<User> getCalls() {
    return calls;
  }
  public void setCalls(List<User> calls) {
    this.calls = calls;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20022 inlineResponse20022 = (InlineResponse20022) o;
    return (this.messages == null ? inlineResponse20022.messages == null : this.messages.equals(inlineResponse20022.messages)) &&
        (this.chat == null ? inlineResponse20022.chat == null : this.chat.equals(inlineResponse20022.chat)) &&
        (this.groupChats == null ? inlineResponse20022.groupChats == null : this.groupChats.equals(inlineResponse20022.groupChats)) &&
        (this.users == null ? inlineResponse20022.users == null : this.users.equals(inlineResponse20022.users)) &&
        (this.calls == null ? inlineResponse20022.calls == null : this.calls.equals(inlineResponse20022.calls));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.messages == null ? 0: this.messages.hashCode());
    result = 31 * result + (this.chat == null ? 0: this.chat.hashCode());
    result = 31 * result + (this.groupChats == null ? 0: this.groupChats.hashCode());
    result = 31 * result + (this.users == null ? 0: this.users.hashCode());
    result = 31 * result + (this.calls == null ? 0: this.calls.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20022 {\n");
    
    sb.append("  messages: ").append(messages).append("\n");
    sb.append("  chat: ").append(chat).append("\n");
    sb.append("  groupChats: ").append(groupChats).append("\n");
    sb.append("  users: ").append(users).append("\n");
    sb.append("  calls: ").append(calls).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
