/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2007MessageMediaArray {
  
  @SerializedName("media_file_string")
  private String mediaFileString = null;
  @SerializedName("media_file")
  private String mediaFile = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMediaFileString() {
    return mediaFileString;
  }
  public void setMediaFileString(String mediaFileString) {
    this.mediaFileString = mediaFileString;
  }

  /**
   * The url of the link to the file
   **/
  @ApiModelProperty(value = "The url of the link to the file")
  public String getMediaFile() {
    return mediaFile;
  }
  public void setMediaFile(String mediaFile) {
    this.mediaFile = mediaFile;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2007MessageMediaArray inlineResponse2007MessageMediaArray = (InlineResponse2007MessageMediaArray) o;
    return (this.mediaFileString == null ? inlineResponse2007MessageMediaArray.mediaFileString == null : this.mediaFileString.equals(inlineResponse2007MessageMediaArray.mediaFileString)) &&
        (this.mediaFile == null ? inlineResponse2007MessageMediaArray.mediaFile == null : this.mediaFile.equals(inlineResponse2007MessageMediaArray.mediaFile));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.mediaFileString == null ? 0: this.mediaFileString.hashCode());
    result = 31 * result + (this.mediaFile == null ? 0: this.mediaFile.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2007MessageMediaArray {\n");
    
    sb.append("  mediaFileString: ").append(mediaFileString).append("\n");
    sb.append("  mediaFile: ").append(mediaFile).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
