/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.InlineResponse2001UnreadMessages;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2004 {
  
  @SerializedName("favoriteMessages")
  private List<InlineResponse2001UnreadMessages> favoriteMessages = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<InlineResponse2001UnreadMessages> getFavoriteMessages() {
    return favoriteMessages;
  }
  public void setFavoriteMessages(List<InlineResponse2001UnreadMessages> favoriteMessages) {
    this.favoriteMessages = favoriteMessages;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2004 inlineResponse2004 = (InlineResponse2004) o;
    return (this.favoriteMessages == null ? inlineResponse2004.favoriteMessages == null : this.favoriteMessages.equals(inlineResponse2004.favoriteMessages));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.favoriteMessages == null ? 0: this.favoriteMessages.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2004 {\n");
    
    sb.append("  favoriteMessages: ").append(favoriteMessages).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
