/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2007MessageFiles {
  
  @SerializedName("file_string")
  private String fileString = null;
  @SerializedName("url")
  private String url = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFileString() {
    return fileString;
  }
  public void setFileString(String fileString) {
    this.fileString = fileString;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2007MessageFiles inlineResponse2007MessageFiles = (InlineResponse2007MessageFiles) o;
    return (this.fileString == null ? inlineResponse2007MessageFiles.fileString == null : this.fileString.equals(inlineResponse2007MessageFiles.fileString)) &&
        (this.url == null ? inlineResponse2007MessageFiles.url == null : this.url.equals(inlineResponse2007MessageFiles.url));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.fileString == null ? 0: this.fileString.hashCode());
    result = 31 * result + (this.url == null ? 0: this.url.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2007MessageFiles {\n");
    
    sb.append("  fileString: ").append(fileString).append("\n");
    sb.append("  url: ").append(url).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
