/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.InlineResponse2001UnreadMessages;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2002 {
  
  @SerializedName("deliveredMessages")
  private List<InlineResponse2001UnreadMessages> deliveredMessages = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<InlineResponse2001UnreadMessages> getDeliveredMessages() {
    return deliveredMessages;
  }
  public void setDeliveredMessages(List<InlineResponse2001UnreadMessages> deliveredMessages) {
    this.deliveredMessages = deliveredMessages;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2002 inlineResponse2002 = (InlineResponse2002) o;
    return (this.deliveredMessages == null ? inlineResponse2002.deliveredMessages == null : this.deliveredMessages.equals(inlineResponse2002.deliveredMessages));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.deliveredMessages == null ? 0: this.deliveredMessages.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2002 {\n");
    
    sb.append("  deliveredMessages: ").append(deliveredMessages).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
