/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.InlineResponse2007MessageFiles;
import io.swagger.client.model.InlineResponse2007MessageMediaArray;
import io.swagger.client.model.InlineResponse2007MessageUser;
import java.math.BigDecimal;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2007Message {
  
  @SerializedName("id")
  private BigDecimal id = null;
  @SerializedName("message")
  private String message = null;
  @SerializedName("call")
  private String call = null;
  @SerializedName("chatId")
  private String chatId = null;
  @SerializedName("userId")
  private String userId = null;
  @SerializedName("type")
  private String type = null;
  @SerializedName("createdAt")
  private String createdAt = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("user")
  private InlineResponse2007MessageUser user = null;
  @SerializedName("mediaArray")
  private List<InlineResponse2007MessageMediaArray> mediaArray = null;
  @SerializedName("files")
  private List<InlineResponse2007MessageFiles> files = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getId() {
    return id;
  }
  public void setId(BigDecimal id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }
  public void setMessage(String message) {
    this.message = message;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCall() {
    return call;
  }
  public void setCall(String call) {
    this.call = call;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getChatId() {
    return chatId;
  }
  public void setChatId(String chatId) {
    this.chatId = chatId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUserId() {
    return userId;
  }
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   * The date time of when the message was created (sent) or the call  made
   **/
  @ApiModelProperty(value = "The date time of when the message was created (sent) or the call  made")
  public String getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  /**
   * The full name of the user who sent the message or called
   **/
  @ApiModelProperty(value = "The full name of the user who sent the message or called")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public InlineResponse2007MessageUser getUser() {
    return user;
  }
  public void setUser(InlineResponse2007MessageUser user) {
    this.user = user;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<InlineResponse2007MessageMediaArray> getMediaArray() {
    return mediaArray;
  }
  public void setMediaArray(List<InlineResponse2007MessageMediaArray> mediaArray) {
    this.mediaArray = mediaArray;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<InlineResponse2007MessageFiles> getFiles() {
    return files;
  }
  public void setFiles(List<InlineResponse2007MessageFiles> files) {
    this.files = files;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2007Message inlineResponse2007Message = (InlineResponse2007Message) o;
    return (this.id == null ? inlineResponse2007Message.id == null : this.id.equals(inlineResponse2007Message.id)) &&
        (this.message == null ? inlineResponse2007Message.message == null : this.message.equals(inlineResponse2007Message.message)) &&
        (this.call == null ? inlineResponse2007Message.call == null : this.call.equals(inlineResponse2007Message.call)) &&
        (this.chatId == null ? inlineResponse2007Message.chatId == null : this.chatId.equals(inlineResponse2007Message.chatId)) &&
        (this.userId == null ? inlineResponse2007Message.userId == null : this.userId.equals(inlineResponse2007Message.userId)) &&
        (this.type == null ? inlineResponse2007Message.type == null : this.type.equals(inlineResponse2007Message.type)) &&
        (this.createdAt == null ? inlineResponse2007Message.createdAt == null : this.createdAt.equals(inlineResponse2007Message.createdAt)) &&
        (this.name == null ? inlineResponse2007Message.name == null : this.name.equals(inlineResponse2007Message.name)) &&
        (this.user == null ? inlineResponse2007Message.user == null : this.user.equals(inlineResponse2007Message.user)) &&
        (this.mediaArray == null ? inlineResponse2007Message.mediaArray == null : this.mediaArray.equals(inlineResponse2007Message.mediaArray)) &&
        (this.files == null ? inlineResponse2007Message.files == null : this.files.equals(inlineResponse2007Message.files));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.message == null ? 0: this.message.hashCode());
    result = 31 * result + (this.call == null ? 0: this.call.hashCode());
    result = 31 * result + (this.chatId == null ? 0: this.chatId.hashCode());
    result = 31 * result + (this.userId == null ? 0: this.userId.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.createdAt == null ? 0: this.createdAt.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.user == null ? 0: this.user.hashCode());
    result = 31 * result + (this.mediaArray == null ? 0: this.mediaArray.hashCode());
    result = 31 * result + (this.files == null ? 0: this.files.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2007Message {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  message: ").append(message).append("\n");
    sb.append("  call: ").append(call).append("\n");
    sb.append("  chatId: ").append(chatId).append("\n");
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  createdAt: ").append(createdAt).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  user: ").append(user).append("\n");
    sb.append("  mediaArray: ").append(mediaArray).append("\n");
    sb.append("  files: ").append(files).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
