/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.InlineResponse20017Messages;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse20017 {
  
  @SerializedName("messages")
  private InlineResponse20017Messages messages = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public InlineResponse20017Messages getMessages() {
    return messages;
  }
  public void setMessages(InlineResponse20017Messages messages) {
    this.messages = messages;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20017 inlineResponse20017 = (InlineResponse20017) o;
    return (this.messages == null ? inlineResponse20017.messages == null : this.messages.equals(inlineResponse20017.messages));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.messages == null ? 0: this.messages.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20017 {\n");
    
    sb.append("  messages: ").append(messages).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
