/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Media {
  
  @SerializedName("id")
  private BigDecimal id = null;
  @SerializedName("media_file_string")
  private String mediaFileString = null;
  @SerializedName("media_file")
  private String mediaFile = null;
  @SerializedName("user_id")
  private BigDecimal userId = null;
  @SerializedName("groupChatId")
  private BigDecimal groupChatId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getId() {
    return id;
  }
  public void setId(BigDecimal id) {
    this.id = id;
  }

  /**
   * In the media table, there is a getter function which retrieves the AWS bucket file which this media object is assoicated with
   **/
  @ApiModelProperty(value = "In the media table, there is a getter function which retrieves the AWS bucket file which this media object is assoicated with")
  public String getMediaFileString() {
    return mediaFileString;
  }
  public void setMediaFileString(String mediaFileString) {
    this.mediaFileString = mediaFileString;
  }

  /**
   * The URL which the file can be uploaded from
   **/
  @ApiModelProperty(value = "The URL which the file can be uploaded from")
  public String getMediaFile() {
    return mediaFile;
  }
  public void setMediaFile(String mediaFile) {
    this.mediaFile = mediaFile;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getUserId() {
    return userId;
  }
  public void setUserId(BigDecimal userId) {
    this.userId = userId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getGroupChatId() {
    return groupChatId;
  }
  public void setGroupChatId(BigDecimal groupChatId) {
    this.groupChatId = groupChatId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Media media = (Media) o;
    return (this.id == null ? media.id == null : this.id.equals(media.id)) &&
        (this.mediaFileString == null ? media.mediaFileString == null : this.mediaFileString.equals(media.mediaFileString)) &&
        (this.mediaFile == null ? media.mediaFile == null : this.mediaFile.equals(media.mediaFile)) &&
        (this.userId == null ? media.userId == null : this.userId.equals(media.userId)) &&
        (this.groupChatId == null ? media.groupChatId == null : this.groupChatId.equals(media.groupChatId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.mediaFileString == null ? 0: this.mediaFileString.hashCode());
    result = 31 * result + (this.mediaFile == null ? 0: this.mediaFile.hashCode());
    result = 31 * result + (this.userId == null ? 0: this.userId.hashCode());
    result = 31 * result + (this.groupChatId == null ? 0: this.groupChatId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Media {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  mediaFileString: ").append(mediaFileString).append("\n");
    sb.append("  mediaFile: ").append(mediaFile).append("\n");
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("  groupChatId: ").append(groupChatId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
