/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.InlineResponse2007MessageMediaArray;
import io.swagger.client.model.InlineResponse2007MessageUser;
import io.swagger.client.model.MessageFiles;
import io.swagger.client.model.MessageGroupChat;
import java.math.BigDecimal;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Message {
  
  @SerializedName("id")
  private BigDecimal id = null;
  @SerializedName("message")
  private String message = null;
  @SerializedName("chatId")
  private String chatId = null;
  @SerializedName("userId")
  private String userId = null;
  @SerializedName("type")
  private String type = null;
  @SerializedName("createdAt")
  private String createdAt = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("post")
  private Boolean post = null;
  @SerializedName("user")
  private InlineResponse2007MessageUser user = null;
  @SerializedName("GroupChat")
  private MessageGroupChat groupChat = null;
  @SerializedName("mediaArray")
  private List<InlineResponse2007MessageMediaArray> mediaArray = null;
  @SerializedName("files")
  private List<MessageFiles> files = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getId() {
    return id;
  }
  public void setId(BigDecimal id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }
  public void setMessage(String message) {
    this.message = message;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getChatId() {
    return chatId;
  }
  public void setChatId(String chatId) {
    this.chatId = chatId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUserId() {
    return userId;
  }
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   * The date time of when the message was created (sent)
   **/
  @ApiModelProperty(value = "The date time of when the message was created (sent)")
  public String getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  /**
   * The full name of the user who sent the message
   **/
  @ApiModelProperty(value = "The full name of the user who sent the message")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getPost() {
    return post;
  }
  public void setPost(Boolean post) {
    this.post = post;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public InlineResponse2007MessageUser getUser() {
    return user;
  }
  public void setUser(InlineResponse2007MessageUser user) {
    this.user = user;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public MessageGroupChat getGroupChat() {
    return groupChat;
  }
  public void setGroupChat(MessageGroupChat groupChat) {
    this.groupChat = groupChat;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<InlineResponse2007MessageMediaArray> getMediaArray() {
    return mediaArray;
  }
  public void setMediaArray(List<InlineResponse2007MessageMediaArray> mediaArray) {
    this.mediaArray = mediaArray;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<MessageFiles> getFiles() {
    return files;
  }
  public void setFiles(List<MessageFiles> files) {
    this.files = files;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Message message = (Message) o;
    return (this.id == null ? message.id == null : this.id.equals(message.id)) &&
        (this.message == null ? message.message == null : this.message.equals(message.message)) &&
        (this.chatId == null ? message.chatId == null : this.chatId.equals(message.chatId)) &&
        (this.userId == null ? message.userId == null : this.userId.equals(message.userId)) &&
        (this.type == null ? message.type == null : this.type.equals(message.type)) &&
        (this.createdAt == null ? message.createdAt == null : this.createdAt.equals(message.createdAt)) &&
        (this.name == null ? message.name == null : this.name.equals(message.name)) &&
        (this.post == null ? message.post == null : this.post.equals(message.post)) &&
        (this.user == null ? message.user == null : this.user.equals(message.user)) &&
        (this.groupChat == null ? message.groupChat == null : this.groupChat.equals(message.groupChat)) &&
        (this.mediaArray == null ? message.mediaArray == null : this.mediaArray.equals(message.mediaArray)) &&
        (this.files == null ? message.files == null : this.files.equals(message.files));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.message == null ? 0: this.message.hashCode());
    result = 31 * result + (this.chatId == null ? 0: this.chatId.hashCode());
    result = 31 * result + (this.userId == null ? 0: this.userId.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.createdAt == null ? 0: this.createdAt.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.post == null ? 0: this.post.hashCode());
    result = 31 * result + (this.user == null ? 0: this.user.hashCode());
    result = 31 * result + (this.groupChat == null ? 0: this.groupChat.hashCode());
    result = 31 * result + (this.mediaArray == null ? 0: this.mediaArray.hashCode());
    result = 31 * result + (this.files == null ? 0: this.files.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Message {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  message: ").append(message).append("\n");
    sb.append("  chatId: ").append(chatId).append("\n");
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  createdAt: ").append(createdAt).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  post: ").append(post).append("\n");
    sb.append("  user: ").append(user).append("\n");
    sb.append("  groupChat: ").append(groupChat).append("\n");
    sb.append("  mediaArray: ").append(mediaArray).append("\n");
    sb.append("  files: ").append(files).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
