/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class MessageFiles {
  
  @SerializedName("file_string")
  private String fileString = null;
  @SerializedName("s3_url")
  private String s3Url = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFileString() {
    return fileString;
  }
  public void setFileString(String fileString) {
    this.fileString = fileString;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getS3Url() {
    return s3Url;
  }
  public void setS3Url(String s3Url) {
    this.s3Url = s3Url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageFiles messageFiles = (MessageFiles) o;
    return (this.fileString == null ? messageFiles.fileString == null : this.fileString.equals(messageFiles.fileString)) &&
        (this.s3Url == null ? messageFiles.s3Url == null : this.s3Url.equals(messageFiles.s3Url));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.fileString == null ? 0: this.fileString.hashCode());
    result = 31 * result + (this.s3Url == null ? 0: this.s3Url.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageFiles {\n");
    
    sb.append("  fileString: ").append(fileString).append("\n");
    sb.append("  s3Url: ").append(s3Url).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
