/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Relationship {
  
  @SerializedName("request_sender")
  private String requestSender = null;
  @SerializedName("request_receiver")
  private String requestReceiver = null;
  @SerializedName("status")
  private String status = null;

  /**
   * foreign key of one user
   **/
  @ApiModelProperty(value = "foreign key of one user")
  public String getRequestSender() {
    return requestSender;
  }
  public void setRequestSender(String requestSender) {
    this.requestSender = requestSender;
  }

  /**
   * foreign key of another user
   **/
  @ApiModelProperty(value = "foreign key of another user")
  public String getRequestReceiver() {
    return requestReceiver;
  }
  public void setRequestReceiver(String requestReceiver) {
    this.requestReceiver = requestReceiver;
  }

  /**
   * Either friends or blocked
   **/
  @ApiModelProperty(value = "Either friends or blocked")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Relationship relationship = (Relationship) o;
    return (this.requestSender == null ? relationship.requestSender == null : this.requestSender.equals(relationship.requestSender)) &&
        (this.requestReceiver == null ? relationship.requestReceiver == null : this.requestReceiver.equals(relationship.requestReceiver)) &&
        (this.status == null ? relationship.status == null : this.status.equals(relationship.status));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.requestSender == null ? 0: this.requestSender.hashCode());
    result = 31 * result + (this.requestReceiver == null ? 0: this.requestReceiver.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Relationship {\n");
    
    sb.append("  requestSender: ").append(requestSender).append("\n");
    sb.append("  requestReceiver: ").append(requestReceiver).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
