/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiInvoker;
import io.swagger.client.ApiException;
import io.swagger.client.Pair;

import io.swagger.client.model.*;

import java.util.*;

import com.android.volley.Response;
import com.android.volley.VolleyError;

import io.swagger.client.model.Body5;
import io.swagger.client.model.Chat;
import io.swagger.client.model.InlineResponse20014;

import org.apache.http.HttpEntity;
import org.apache.http.entity.mime.MultipartEntityBuilder;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeoutException;

public class PrivatechatApi {
  String basePath = "https://virtserver.swaggerhub.com/asterakia/WhatsApp/1.0.0";
  ApiInvoker apiInvoker = ApiInvoker.getInstance();

  public void addHeader(String key, String value) {
    getInvoker().addDefaultHeader(key, value);
  }

  public ApiInvoker getInvoker() {
    return apiInvoker;
  }

  public void setBasePath(String basePath) {
    this.basePath = basePath;
  }

  public String getBasePath() {
    return basePath;
  }

  /**
  * Delete a private chat
  * 
   * @param chatId The ID of a specific chat
   * @return Chat
  */
  public Chat privateChatsChatIdDelete (String chatId) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'chatId' is set
    if (chatId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'chatId' when calling privateChatsChatIdDelete",
        new ApiException(400, "Missing the required parameter 'chatId' when calling privateChatsChatIdDelete"));
    }

    // create path and map variables
    String path = "/privateChats/{chatId}".replaceAll("\\{" + "chatId" + "\\}", apiInvoker.escapeString(chatId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "Authorization" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "DELETE", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (Chat) ApiInvoker.deserialize(localVarResponse, "", Chat.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Delete a private chat
   * 
   * @param chatId The ID of a specific chat
  */
  public void privateChatsChatIdDelete (String chatId, final Response.Listener<Chat> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'chatId' is set
    if (chatId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'chatId' when calling privateChatsChatIdDelete",
        new ApiException(400, "Missing the required parameter 'chatId' when calling privateChatsChatIdDelete"));
    }

    // create path and map variables
    String path = "/privateChats/{chatId}".replaceAll("\\{format\\}","json").replaceAll("\\{" + "chatId" + "\\}", apiInvoker.escapeString(chatId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "Authorization" };

    try {
      apiInvoker.invokeAPI(basePath, path, "DELETE", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((Chat) ApiInvoker.deserialize(localVarResponse,  "", Chat.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Favorite a specific private chat
  * 
   * @param chatId 
   * @param body 
   * @return Chat
  */
  public Chat privateChatsChatIdFavoritePut (String chatId, Body5 body) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = body;
    // verify the required parameter 'chatId' is set
    if (chatId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'chatId' when calling privateChatsChatIdFavoritePut",
        new ApiException(400, "Missing the required parameter 'chatId' when calling privateChatsChatIdFavoritePut"));
    }
    // verify the required parameter 'body' is set
    if (body == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'body' when calling privateChatsChatIdFavoritePut",
        new ApiException(400, "Missing the required parameter 'body' when calling privateChatsChatIdFavoritePut"));
    }

    // create path and map variables
    String path = "/privateChats/{chatId}/favorite".replaceAll("\\{" + "chatId" + "\\}", apiInvoker.escapeString(chatId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "Authorization" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "PUT", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (Chat) ApiInvoker.deserialize(localVarResponse, "", Chat.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Favorite a specific private chat
   * 
   * @param chatId    * @param body 
  */
  public void privateChatsChatIdFavoritePut (String chatId, Body5 body, final Response.Listener<Chat> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = body;

    // verify the required parameter 'chatId' is set
    if (chatId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'chatId' when calling privateChatsChatIdFavoritePut",
        new ApiException(400, "Missing the required parameter 'chatId' when calling privateChatsChatIdFavoritePut"));
    }
    // verify the required parameter 'body' is set
    if (body == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'body' when calling privateChatsChatIdFavoritePut",
        new ApiException(400, "Missing the required parameter 'body' when calling privateChatsChatIdFavoritePut"));
    }

    // create path and map variables
    String path = "/privateChats/{chatId}/favorite".replaceAll("\\{format\\}","json").replaceAll("\\{" + "chatId" + "\\}", apiInvoker.escapeString(chatId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "Authorization" };

    try {
      apiInvoker.invokeAPI(basePath, path, "PUT", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((Chat) ApiInvoker.deserialize(localVarResponse,  "", Chat.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Get 40 messages belonging to a private chat.
  * 
   * @param userId 
   * @param chatId 
   * @param messageId Include this query parameter when you would like to get the next 40 messages following a specific message. If this query parameter is not included, you will get the 40 newest messages in order
   * @return InlineResponse20014
  */
  public InlineResponse20014 privateChatsChatIdUserUserIdMessagesGet (String userId, String chatId, String messageId) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'userId' is set
    if (userId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'userId' when calling privateChatsChatIdUserUserIdMessagesGet",
        new ApiException(400, "Missing the required parameter 'userId' when calling privateChatsChatIdUserUserIdMessagesGet"));
    }
    // verify the required parameter 'chatId' is set
    if (chatId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'chatId' when calling privateChatsChatIdUserUserIdMessagesGet",
        new ApiException(400, "Missing the required parameter 'chatId' when calling privateChatsChatIdUserUserIdMessagesGet"));
    }

    // create path and map variables
    String path = "/privateChats/{chatId}/user/{userId}/messages".replaceAll("\\{" + "userId" + "\\}", apiInvoker.escapeString(userId.toString())).replaceAll("\\{" + "chatId" + "\\}", apiInvoker.escapeString(chatId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    queryParams.addAll(ApiInvoker.parameterToPairs("", "messageId", messageId));
    String[] contentTypes = {
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "Authorization" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (InlineResponse20014) ApiInvoker.deserialize(localVarResponse, "", InlineResponse20014.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Get 40 messages belonging to a private chat.
   * 
   * @param userId    * @param chatId    * @param messageId Include this query parameter when you would like to get the next 40 messages following a specific message. If this query parameter is not included, you will get the 40 newest messages in order
  */
  public void privateChatsChatIdUserUserIdMessagesGet (String userId, String chatId, String messageId, final Response.Listener<InlineResponse20014> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'userId' is set
    if (userId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'userId' when calling privateChatsChatIdUserUserIdMessagesGet",
        new ApiException(400, "Missing the required parameter 'userId' when calling privateChatsChatIdUserUserIdMessagesGet"));
    }
    // verify the required parameter 'chatId' is set
    if (chatId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'chatId' when calling privateChatsChatIdUserUserIdMessagesGet",
        new ApiException(400, "Missing the required parameter 'chatId' when calling privateChatsChatIdUserUserIdMessagesGet"));
    }

    // create path and map variables
    String path = "/privateChats/{chatId}/user/{userId}/messages".replaceAll("\\{format\\}","json").replaceAll("\\{" + "userId" + "\\}", apiInvoker.escapeString(userId.toString())).replaceAll("\\{" + "chatId" + "\\}", apiInvoker.escapeString(chatId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();

    queryParams.addAll(ApiInvoker.parameterToPairs("", "messageId", messageId));


    String[] contentTypes = {
      
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "Authorization" };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((InlineResponse20014) ApiInvoker.deserialize(localVarResponse,  "", InlineResponse20014.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Create a private chat between two users
  * 
   * @param userIds Only two userIds can be sent for this endpoint due to the fact that you are creating a private chat
   * @return Chat
  */
  public Chat privateChatsPost (List<String> userIds) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;

    // create path and map variables
    String path = "/privateChats";

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "multipart/form-data"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      if (userIds != null) {
        localVarBuilder.addTextBody("userIds", ApiInvoker.parameterToString(userIds), ApiInvoker.TEXT_PLAIN_UTF8);
      }
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
      formParams.put("userIds", ApiInvoker.parameterToString(userIds));
    }

    String[] authNames = new String[] { "Authorization", "Socket" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "POST", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (Chat) ApiInvoker.deserialize(localVarResponse, "", Chat.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Create a private chat between two users
   * 
   * @param userIds Only two userIds can be sent for this endpoint due to the fact that you are creating a private chat
  */
  public void privateChatsPost (List<String> userIds, final Response.Listener<Chat> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;


    // create path and map variables
    String path = "/privateChats".replaceAll("\\{format\\}","json");

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "multipart/form-data"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      
      if (userIds != null) {
        localVarBuilder.addTextBody("userIds", ApiInvoker.parameterToString(userIds), ApiInvoker.TEXT_PLAIN_UTF8);
      }
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
      formParams.put("userIds", ApiInvoker.parameterToString(userIds));
    }

    String[] authNames = new String[] { "Authorization", "Socket" };

    try {
      apiInvoker.invokeAPI(basePath, path, "POST", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((Chat) ApiInvoker.deserialize(localVarResponse,  "", Chat.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
}
