/**
 * Whats App API
 * Whats App API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: irma.tabakis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonParseException;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.List;
import java.util.Date;
import io.swagger.client.model.*;

public class JsonUtil {
  public static GsonBuilder gsonBuilder;

  static {
    gsonBuilder = new GsonBuilder();
    gsonBuilder.serializeNulls();
    gsonBuilder.setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
    gsonBuilder.registerTypeAdapter(Date.class, new JsonDeserializer<Date>() {
      public Date deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
        return new Date(json.getAsJsonPrimitive().getAsLong());
      }
    });
  }

  public static Gson getGson() {
    return gsonBuilder.create();
  }

  public static String serialize(Object obj){
    return getGson().toJson(obj);
  }

  public static <T> T deserializeToList(String jsonString, Class cls){
    return getGson().fromJson(jsonString, getListTypeForDeserialization(cls));
  }

  public static <T> T deserializeToObject(String jsonString, Class cls){
    return getGson().fromJson(jsonString, getTypeForDeserialization(cls));
  }

  public static Type getListTypeForDeserialization(Class cls) {
    String className = cls.getSimpleName();
    
    if ("Body".equalsIgnoreCase(className)) {
      return new TypeToken<List<Body>>(){}.getType();
    }
    
    if ("Body1".equalsIgnoreCase(className)) {
      return new TypeToken<List<Body1>>(){}.getType();
    }
    
    if ("Body10".equalsIgnoreCase(className)) {
      return new TypeToken<List<Body10>>(){}.getType();
    }
    
    if ("Body11".equalsIgnoreCase(className)) {
      return new TypeToken<List<Body11>>(){}.getType();
    }
    
    if ("Body12".equalsIgnoreCase(className)) {
      return new TypeToken<List<Body12>>(){}.getType();
    }
    
    if ("Body2".equalsIgnoreCase(className)) {
      return new TypeToken<List<Body2>>(){}.getType();
    }
    
    if ("Body3".equalsIgnoreCase(className)) {
      return new TypeToken<List<Body3>>(){}.getType();
    }
    
    if ("Body4".equalsIgnoreCase(className)) {
      return new TypeToken<List<Body4>>(){}.getType();
    }
    
    if ("Body5".equalsIgnoreCase(className)) {
      return new TypeToken<List<Body5>>(){}.getType();
    }
    
    if ("Body6".equalsIgnoreCase(className)) {
      return new TypeToken<List<Body6>>(){}.getType();
    }
    
    if ("Body7".equalsIgnoreCase(className)) {
      return new TypeToken<List<Body7>>(){}.getType();
    }
    
    if ("Body8".equalsIgnoreCase(className)) {
      return new TypeToken<List<Body8>>(){}.getType();
    }
    
    if ("Body9".equalsIgnoreCase(className)) {
      return new TypeToken<List<Body9>>(){}.getType();
    }
    
    if ("Chat".equalsIgnoreCase(className)) {
      return new TypeToken<List<Chat>>(){}.getType();
    }
    
    if ("GroupChat".equalsIgnoreCase(className)) {
      return new TypeToken<List<GroupChat>>(){}.getType();
    }
    
    if ("InlineResponse200".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse200>>(){}.getType();
    }
    
    if ("InlineResponse2001".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse2001>>(){}.getType();
    }
    
    if ("InlineResponse20010".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20010>>(){}.getType();
    }
    
    if ("InlineResponse20011".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20011>>(){}.getType();
    }
    
    if ("InlineResponse20012".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20012>>(){}.getType();
    }
    
    if ("InlineResponse20012MediaArray".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20012MediaArray>>(){}.getType();
    }
    
    if ("InlineResponse20013".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20013>>(){}.getType();
    }
    
    if ("InlineResponse20013SharedMedia".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20013SharedMedia>>(){}.getType();
    }
    
    if ("InlineResponse20014".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20014>>(){}.getType();
    }
    
    if ("InlineResponse20014Messages".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20014Messages>>(){}.getType();
    }
    
    if ("InlineResponse20014MessagesFiles".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20014MessagesFiles>>(){}.getType();
    }
    
    if ("InlineResponse20014MessagesRead".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20014MessagesRead>>(){}.getType();
    }
    
    if ("InlineResponse20014MessagesUnread".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20014MessagesUnread>>(){}.getType();
    }
    
    if ("InlineResponse20015".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20015>>(){}.getType();
    }
    
    if ("InlineResponse20015Chat".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20015Chat>>(){}.getType();
    }
    
    if ("InlineResponse20016".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20016>>(){}.getType();
    }
    
    if ("InlineResponse20017".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20017>>(){}.getType();
    }
    
    if ("InlineResponse20017Messages".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20017Messages>>(){}.getType();
    }
    
    if ("InlineResponse20017MessagesFiles".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20017MessagesFiles>>(){}.getType();
    }
    
    if ("InlineResponse20017MessagesUnread".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20017MessagesUnread>>(){}.getType();
    }
    
    if ("InlineResponse20018".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20018>>(){}.getType();
    }
    
    if ("InlineResponse20019".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20019>>(){}.getType();
    }
    
    if ("InlineResponse2001UnreadMessages".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse2001UnreadMessages>>(){}.getType();
    }
    
    if ("InlineResponse2002".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse2002>>(){}.getType();
    }
    
    if ("InlineResponse20020".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20020>>(){}.getType();
    }
    
    if ("InlineResponse20020MediaArray".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20020MediaArray>>(){}.getType();
    }
    
    if ("InlineResponse20021".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20021>>(){}.getType();
    }
    
    if ("InlineResponse20022".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse20022>>(){}.getType();
    }
    
    if ("InlineResponse2003".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse2003>>(){}.getType();
    }
    
    if ("InlineResponse2004".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse2004>>(){}.getType();
    }
    
    if ("InlineResponse2005".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse2005>>(){}.getType();
    }
    
    if ("InlineResponse2005NonAnsweredCalls".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse2005NonAnsweredCalls>>(){}.getType();
    }
    
    if ("InlineResponse2006".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse2006>>(){}.getType();
    }
    
    if ("InlineResponse2007".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse2007>>(){}.getType();
    }
    
    if ("InlineResponse2007Chats".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse2007Chats>>(){}.getType();
    }
    
    if ("InlineResponse2007GroupChatInfo".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse2007GroupChatInfo>>(){}.getType();
    }
    
    if ("InlineResponse2007Message".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse2007Message>>(){}.getType();
    }
    
    if ("InlineResponse2007MessageFiles".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse2007MessageFiles>>(){}.getType();
    }
    
    if ("InlineResponse2007MessageMediaArray".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse2007MessageMediaArray>>(){}.getType();
    }
    
    if ("InlineResponse2007MessageUser".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse2007MessageUser>>(){}.getType();
    }
    
    if ("InlineResponse2007User".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse2007User>>(){}.getType();
    }
    
    if ("InlineResponse2008".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse2008>>(){}.getType();
    }
    
    if ("InlineResponse2009".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse2009>>(){}.getType();
    }
    
    if ("InlineResponse200User".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse200User>>(){}.getType();
    }
    
    if ("InlineResponse500".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse500>>(){}.getType();
    }
    
    if ("InlineResponse500Messages".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse500Messages>>(){}.getType();
    }
    
    if ("Media".equalsIgnoreCase(className)) {
      return new TypeToken<List<Media>>(){}.getType();
    }
    
    if ("Message".equalsIgnoreCase(className)) {
      return new TypeToken<List<Message>>(){}.getType();
    }
    
    if ("MessageFiles".equalsIgnoreCase(className)) {
      return new TypeToken<List<MessageFiles>>(){}.getType();
    }
    
    if ("MessageGroupChat".equalsIgnoreCase(className)) {
      return new TypeToken<List<MessageGroupChat>>(){}.getType();
    }
    
    if ("Relationship".equalsIgnoreCase(className)) {
      return new TypeToken<List<Relationship>>(){}.getType();
    }
    
    if ("User".equalsIgnoreCase(className)) {
      return new TypeToken<List<User>>(){}.getType();
    }
    
    if ("UserChats".equalsIgnoreCase(className)) {
      return new TypeToken<List<UserChats>>(){}.getType();
    }
    
    return new TypeToken<List<Object>>(){}.getType();
  }

  public static Type getTypeForDeserialization(Class cls) {
    String className = cls.getSimpleName();
    
    if ("Body".equalsIgnoreCase(className)) {
      return new TypeToken<Body>(){}.getType();
    }
    
    if ("Body1".equalsIgnoreCase(className)) {
      return new TypeToken<Body1>(){}.getType();
    }
    
    if ("Body10".equalsIgnoreCase(className)) {
      return new TypeToken<Body10>(){}.getType();
    }
    
    if ("Body11".equalsIgnoreCase(className)) {
      return new TypeToken<Body11>(){}.getType();
    }
    
    if ("Body12".equalsIgnoreCase(className)) {
      return new TypeToken<Body12>(){}.getType();
    }
    
    if ("Body2".equalsIgnoreCase(className)) {
      return new TypeToken<Body2>(){}.getType();
    }
    
    if ("Body3".equalsIgnoreCase(className)) {
      return new TypeToken<Body3>(){}.getType();
    }
    
    if ("Body4".equalsIgnoreCase(className)) {
      return new TypeToken<Body4>(){}.getType();
    }
    
    if ("Body5".equalsIgnoreCase(className)) {
      return new TypeToken<Body5>(){}.getType();
    }
    
    if ("Body6".equalsIgnoreCase(className)) {
      return new TypeToken<Body6>(){}.getType();
    }
    
    if ("Body7".equalsIgnoreCase(className)) {
      return new TypeToken<Body7>(){}.getType();
    }
    
    if ("Body8".equalsIgnoreCase(className)) {
      return new TypeToken<Body8>(){}.getType();
    }
    
    if ("Body9".equalsIgnoreCase(className)) {
      return new TypeToken<Body9>(){}.getType();
    }
    
    if ("Chat".equalsIgnoreCase(className)) {
      return new TypeToken<Chat>(){}.getType();
    }
    
    if ("GroupChat".equalsIgnoreCase(className)) {
      return new TypeToken<GroupChat>(){}.getType();
    }
    
    if ("InlineResponse200".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse200>(){}.getType();
    }
    
    if ("InlineResponse2001".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse2001>(){}.getType();
    }
    
    if ("InlineResponse20010".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20010>(){}.getType();
    }
    
    if ("InlineResponse20011".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20011>(){}.getType();
    }
    
    if ("InlineResponse20012".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20012>(){}.getType();
    }
    
    if ("InlineResponse20012MediaArray".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20012MediaArray>(){}.getType();
    }
    
    if ("InlineResponse20013".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20013>(){}.getType();
    }
    
    if ("InlineResponse20013SharedMedia".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20013SharedMedia>(){}.getType();
    }
    
    if ("InlineResponse20014".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20014>(){}.getType();
    }
    
    if ("InlineResponse20014Messages".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20014Messages>(){}.getType();
    }
    
    if ("InlineResponse20014MessagesFiles".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20014MessagesFiles>(){}.getType();
    }
    
    if ("InlineResponse20014MessagesRead".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20014MessagesRead>(){}.getType();
    }
    
    if ("InlineResponse20014MessagesUnread".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20014MessagesUnread>(){}.getType();
    }
    
    if ("InlineResponse20015".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20015>(){}.getType();
    }
    
    if ("InlineResponse20015Chat".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20015Chat>(){}.getType();
    }
    
    if ("InlineResponse20016".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20016>(){}.getType();
    }
    
    if ("InlineResponse20017".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20017>(){}.getType();
    }
    
    if ("InlineResponse20017Messages".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20017Messages>(){}.getType();
    }
    
    if ("InlineResponse20017MessagesFiles".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20017MessagesFiles>(){}.getType();
    }
    
    if ("InlineResponse20017MessagesUnread".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20017MessagesUnread>(){}.getType();
    }
    
    if ("InlineResponse20018".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20018>(){}.getType();
    }
    
    if ("InlineResponse20019".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20019>(){}.getType();
    }
    
    if ("InlineResponse2001UnreadMessages".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse2001UnreadMessages>(){}.getType();
    }
    
    if ("InlineResponse2002".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse2002>(){}.getType();
    }
    
    if ("InlineResponse20020".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20020>(){}.getType();
    }
    
    if ("InlineResponse20020MediaArray".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20020MediaArray>(){}.getType();
    }
    
    if ("InlineResponse20021".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20021>(){}.getType();
    }
    
    if ("InlineResponse20022".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse20022>(){}.getType();
    }
    
    if ("InlineResponse2003".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse2003>(){}.getType();
    }
    
    if ("InlineResponse2004".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse2004>(){}.getType();
    }
    
    if ("InlineResponse2005".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse2005>(){}.getType();
    }
    
    if ("InlineResponse2005NonAnsweredCalls".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse2005NonAnsweredCalls>(){}.getType();
    }
    
    if ("InlineResponse2006".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse2006>(){}.getType();
    }
    
    if ("InlineResponse2007".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse2007>(){}.getType();
    }
    
    if ("InlineResponse2007Chats".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse2007Chats>(){}.getType();
    }
    
    if ("InlineResponse2007GroupChatInfo".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse2007GroupChatInfo>(){}.getType();
    }
    
    if ("InlineResponse2007Message".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse2007Message>(){}.getType();
    }
    
    if ("InlineResponse2007MessageFiles".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse2007MessageFiles>(){}.getType();
    }
    
    if ("InlineResponse2007MessageMediaArray".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse2007MessageMediaArray>(){}.getType();
    }
    
    if ("InlineResponse2007MessageUser".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse2007MessageUser>(){}.getType();
    }
    
    if ("InlineResponse2007User".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse2007User>(){}.getType();
    }
    
    if ("InlineResponse2008".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse2008>(){}.getType();
    }
    
    if ("InlineResponse2009".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse2009>(){}.getType();
    }
    
    if ("InlineResponse200User".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse200User>(){}.getType();
    }
    
    if ("InlineResponse500".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse500>(){}.getType();
    }
    
    if ("InlineResponse500Messages".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse500Messages>(){}.getType();
    }
    
    if ("Media".equalsIgnoreCase(className)) {
      return new TypeToken<Media>(){}.getType();
    }
    
    if ("Message".equalsIgnoreCase(className)) {
      return new TypeToken<Message>(){}.getType();
    }
    
    if ("MessageFiles".equalsIgnoreCase(className)) {
      return new TypeToken<MessageFiles>(){}.getType();
    }
    
    if ("MessageGroupChat".equalsIgnoreCase(className)) {
      return new TypeToken<MessageGroupChat>(){}.getType();
    }
    
    if ("Relationship".equalsIgnoreCase(className)) {
      return new TypeToken<Relationship>(){}.getType();
    }
    
    if ("User".equalsIgnoreCase(className)) {
      return new TypeToken<User>(){}.getType();
    }
    
    if ("UserChats".equalsIgnoreCase(className)) {
      return new TypeToken<UserChats>(){}.getType();
    }
    
    return new TypeToken<Object>(){}.getType();
  }

};
